apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lcaaj25w2-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lcaaj25w2-python 
  name: lcaaj25w2-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lcaaj25w2-python 
