apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lcaaj25w2-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:90fdda98cf35cd773a7700b4bf1644e189896001@sha256:18c433d4a1b6a0a407c50539cdcc6c79ee25f2db591a785f18f1df599f64c759
          name: container-image
